VIA_ENABLE = no
ENCODER_MAP_ENABLE = yes
BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite
MOUSEKEY_ENABLE = yes       # Mouse keys
EXTRAKEY_ENABLE = no       # Audio control and System control
CONSOLE_ENABLE = no        # Console for debug
COMMAND_ENABLE = no        # Commands for debug and configuration
CAPS_WORD_ENABLE = yes
REPEAT_KEY_ENABLE = yes
LEADER_ENABLE = yes
NKRO_ENABLE = yes           # Enable N-Key Rollover
DYNAMIC_MACRO_ENABLE = yes
TRI_LAYER_ENABLE = yes
