#    define ONESHOT_TAP_TOGGLE 2
#    define TAPPING_TOGGLE 2
#    define TAPPING_TERM 250
#    define TAPPING_TERM_PER_KEY
#    define QUICK_TAPPING_TERM 200
#    define RETRO_TAPPING_PER_KEY
#    define PERMISSIVE_HOLD
#    define LEADER_TIMEOUT 300
#    define LEADER_PER_KEY_TIMING
#    define LEADER_NO_TIMEOUT
#    define ALT_REPEAT_MASK MOD_BIT(KC_RSFT)
#    define UNICODE_SELECTED_MODES UNICODE_MODE_LINUX, UNICODE_MODE_WINCOMPOSE
#    define CAPS_WORD_INVERT_ON_SHIFT
#    define OS_DETECTION_KEYBOARD_RESET
